/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.suny.np.soda.gui;

import edu.suny.np.oop.soda.SodaMachine;

/**
 *
 * @author Frederico Castro
 */
public class Admin extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public Admin(java.awt.Frame parent, boolean modal, SodaMachine newSodaMachine) {
    	super(parent, modal);
        mSodaMachine = newSodaMachine;
        initComponents();
        printCoinReturn();
        printCashBox();
    }
    
    public void printCashBox(){
    	totalTxt.setText(mSodaMachine.getCashBox());
    }
    
    public void printCoinReturn() {
        int[] coins = mSodaMachine.getCoinReturn();
        nickelTxt.setText(Integer.toString(coins[0]));
        dimeTxt.setText(Integer.toString(coins[1]));
        quarterTxt.setText(Integer.toString(coins[2]));
      }
    
    public void printQIS(){
    	int[] inventoryQIS = new int[5];
    	inventoryQIS=mSodaMachine.getInventoryQIS();
    	
    	TxtQisS0.setText(Integer.toString(inventoryQIS[0]));
        TxtQisS1.setText(Integer.toString(inventoryQIS[1]));
        TxtQisS2.setText(Integer.toString(inventoryQIS[2]));
        TxtQisS3.setText(Integer.toString(inventoryQIS[3]));
        TxtQisS4.setText(Integer.toString(inventoryQIS[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        coinReturn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nickelTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dimeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quarterTxt = new javax.swing.JTextField();
        cashBox = new javax.swing.JPanel();
        totalTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        remax = new javax.swing.JButton();
        Inventory = new javax.swing.JPanel();
        InventoryName = new javax.swing.JLabel();
        QIS = new javax.swing.JLabel();
        Restock = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        TxtS0Name = new javax.swing.JTextField();
        TxtS1Name = new javax.swing.JTextField();
        TxtS2Name = new javax.swing.JTextField();
        TxtS3Name = new javax.swing.JTextField();
        TxtS4Name = new javax.swing.JTextField();
        TxtQisS0 = new javax.swing.JTextField();
        TxtQisS1 = new javax.swing.JTextField();
        TxtQisS2 = new javax.swing.JTextField();
        TxtQisS3 = new javax.swing.JTextField();
        TxtQisS4 = new javax.swing.JTextField();
        buttonS0 = new javax.swing.JButton();
        buttonS1 = new javax.swing.JButton();
        buttonS2 = new javax.swing.JButton();
        buttonS3 = new javax.swing.JButton();
        buttonS4 = new javax.swing.JButton();
        quit = new javax.swing.JPanel();
        quitBtn = new javax.swing.JButton();

        

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        title.setText("Admin Mode");

        coinReturn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coin Return", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel1.setText("N");

        nickelTxt.setFocusable(false);

        jLabel2.setText("D");

        dimeTxt.setFocusable(false);
        
        jLabel3.setText("Q");

        quarterTxt.setFocusable(false);
        
        javax.swing.GroupLayout coinReturnLayout = new javax.swing.GroupLayout(coinReturn);
        coinReturn.setLayout(coinReturnLayout);
        coinReturnLayout.setHorizontalGroup(
            coinReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coinReturnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nickelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quarterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coinReturnLayout.setVerticalGroup(
            coinReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coinReturnLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(coinReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coinReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(quarterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(coinReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(dimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(coinReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nickelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        cashBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash Box", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        totalTxt.setFocusable(false);
       
        jLabel4.setText("Total");

        remax.setText("Remax");
        
        javax.swing.GroupLayout cashBoxLayout = new javax.swing.GroupLayout(cashBox);
        cashBox.setLayout(cashBoxLayout);
        cashBoxLayout.setHorizontalGroup(
            cashBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashBoxLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(remax)
                .addGap(23, 23, 23))
        );
        cashBoxLayout.setVerticalGroup(
            cashBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashBoxLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(cashBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(remax))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Inventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        InventoryName.setText("Name");

        QIS.setText("QIS");

        Restock.setText("Restock");

        TxtS0Name.setEditable(false);
        TxtS0Name.setText("Cola");        
        TxtS1Name.setEditable(false);
        TxtS1Name.setText("Orange");        
        TxtS2Name.setEditable(false);
        TxtS2Name.setText("Sprite");        
        TxtS3Name.setEditable(false);
        TxtS3Name.setText("Ginger Ale");       
        TxtS4Name.setEditable(false);
        TxtS4Name.setText("Diet Cola");  

        TxtQisS0.setEditable(false);      
        TxtQisS1.setEditable(false);       
        TxtQisS2.setEditable(false);        
        TxtQisS3.setEditable(false);        
        TxtQisS4.setEditable(false);  

        buttonS0.setText("yes");
        buttonS0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS0ActionPerformed(evt);
            }
        });

        buttonS1.setText("yes");
        buttonS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS1ActionPerformed(evt);
            }
        });

        buttonS2.setText("yes");
        buttonS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS2ActionPerformed(evt);
            }
        });

        buttonS3.setText("yes");
        buttonS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS3ActionPerformed(evt);
            }
        });

        buttonS4.setText("yes");
        buttonS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InventoryLayout = new javax.swing.GroupLayout(Inventory);
        Inventory.setLayout(InventoryLayout);
        InventoryLayout.setHorizontalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(InventoryName)
                .addGap(53, 53, 53)
                .addComponent(QIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Restock)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(InventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addComponent(TxtS0Name, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtQisS0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonS0))
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addComponent(TxtS1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtQisS1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonS1))
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addComponent(TxtS2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtQisS2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonS2))
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addComponent(TxtS3Name, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtQisS3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonS3))
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addComponent(TxtS4Name, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtQisS4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonS4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InventoryLayout.setVerticalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InventoryName)
                    .addComponent(QIS)
                    .addComponent(Restock))
                .addGap(18, 18, 18)
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtS0Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtQisS0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonS0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtS1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtQisS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtS2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtQisS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonS2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtS3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtQisS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonS3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtS4Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtQisS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonS4))
                .addGap(59, 59, 59)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        quit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quitLayout = new javax.swing.GroupLayout(quit);
        quit.setLayout(quitLayout);
        quitLayout.setHorizontalGroup(
            quitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quitLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(quitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quitLayout.setVerticalGroup(
            quitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitBtn)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coinReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cashBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coinReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cashBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        
        this.printQIS();
        this.printCoinReturn();
    }// </editor-fold>                                                                                                  
                                     

    private void buttonS0ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        mSodaMachine.updateInventory("cola");
    }                                        

    private void buttonS1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        mSodaMachine.updateInventory("orange");
    }   

    private void buttonS2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        mSodaMachine.updateInventory("sprite");
    }                                

    private void buttonS3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        mSodaMachine.updateInventory("ginger ale");
    }                                         

    private void buttonS4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        mSodaMachine.updateInventory("diet cola");
    }                                        

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.setVisible(false);
    }                                                             

    private void remaxBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        mSodaMachine.remax();
    } 
     
    
    // Variables declaration - do not modify 
    private SodaMachine mSodaMachine;
    private javax.swing.JPanel Inventory;
    private javax.swing.JLabel InventoryName;
    private javax.swing.JLabel QIS;
    private javax.swing.JLabel Restock;
    private javax.swing.JTextField TxtQisS0;
    private javax.swing.JTextField TxtQisS1;
    private javax.swing.JTextField TxtQisS2;
    private javax.swing.JTextField TxtQisS3;
    private javax.swing.JTextField TxtQisS4;
    private javax.swing.JTextField TxtS0Name;
    private javax.swing.JTextField TxtS1Name;
    private javax.swing.JTextField TxtS2Name;
    private javax.swing.JTextField TxtS3Name;
    private javax.swing.JTextField TxtS4Name;
    private javax.swing.JButton buttonS0;
    private javax.swing.JButton buttonS1;
    private javax.swing.JButton buttonS2;
    private javax.swing.JButton buttonS3;
    private javax.swing.JButton buttonS4;
    private java.awt.Canvas canvas1;
    private javax.swing.JPanel cashBox;
    private javax.swing.JPanel coinReturn;
    private javax.swing.JTextField dimeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nickelTxt;
    private javax.swing.JTextField quarterTxt;
    private javax.swing.JPanel quit;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton remax;
    private javax.swing.JLabel title;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration                   
}
