package edu.suny.np.soda.gui;
import java.awt.Component;
import javax.swing.Box;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.GridBagLayout;
import java.awt.CardLayout;
import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.ColumnSpec;
import com.jgoodies.forms.layout.RowSpec;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JTable;
 
/**
 *
 * @author Frederico Castro
 */
public class SodaMachineAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SodaMachineGui
     */
    public SodaMachineAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        coinEntry = new javax.swing.JPanel();
        cashBox = new javax.swing.JPanel();
        Inventory = new javax.swing.JPanel();
        adminModeSelection = new javax.swing.JPanel();
        quitAdminModeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        title.setText("Admin Mode");

        coinEntry.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coin Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14)));

        cashBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash Box", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14)));

        Inventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14)));
        
        table = new JTable();
        

        Object rowData[][] = { 
                {"Coke", "3", null},
                {"Orange", "0", null},
                {"Sprite", "2", null},
                {"Ginger Ale", "2", null},
                {"Diet Coke", "2", null} };
        Object columnNames[] = { "Name", "Qis", "Restock" };
        JTable table = new JTable(rowData, columnNames);
        
        table.setModel(new javax.swing.table.DefaultTableModel(rowData, columnNames));
               

        javax.swing.GroupLayout InventoryLayout = new javax.swing.GroupLayout(Inventory);
        InventoryLayout.setHorizontalGroup(
        	InventoryLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(InventoryLayout.createSequentialGroup()
        			.addGap(65)
        			.addComponent(table, GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        			.addGap(76))
        );
        InventoryLayout.setVerticalGroup(
        	InventoryLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, InventoryLayout.createSequentialGroup()
        			.addGap(39)
        			.addComponent(table, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(54, Short.MAX_VALUE))
        );
        Inventory.setLayout(InventoryLayout);

        adminModeSelection.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        quitAdminModeButton.setText("Quit");
        quitAdminModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitAdminModeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminModeSelectionLayout = new javax.swing.GroupLayout(adminModeSelection);
        adminModeSelection.setLayout(adminModeSelectionLayout);
        adminModeSelectionLayout.setHorizontalGroup(
            adminModeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminModeSelectionLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(quitAdminModeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminModeSelectionLayout.setVerticalGroup(
            adminModeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminModeSelectionLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(quitAdminModeButton)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Inventory, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(cashBox, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(title)
        					.addGap(152))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(coinEntry, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        						.addComponent(adminModeSelection, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        					.addContainerGap())))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(title)
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addComponent(coinEntry, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cashBox, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(Inventory, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)
        			.addGap(23)
        			.addComponent(adminModeSelection, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        cashBox.setLayout(null);
        
        lblNewLabel = new JLabel("Total");
        lblNewLabel.setBounds(28, 50, 32, 16);
        cashBox.add(lblNewLabel);
        
        textField = new JTextField();
        textField.setEditable(false);
        textField.setBounds(69, 44, 49, 28);
        cashBox.add(textField);
        textField.setColumns(10);
        
        JButton btnRemax = new JButton("Remax");
        btnRemax.setBounds(242, 45, 117, 29);
        cashBox.add(btnRemax);
        coinEntry.setLayout(null);
        
        lblNickel = new JLabel("Nickel");
        lblNickel.setBounds(28, 48, 40, 16);
        coinEntry.add(lblNickel);
        
        nickle = new JTextField();
        nickle.setEditable(false);
        nickle.setBounds(83, 42, 45, 28);
        coinEntry.add(nickle);
        nickle.setColumns(10);
        
        dime = new JTextField();
        dime.setEditable(false);
        dime.setColumns(10);
        dime.setBounds(191, 42, 45, 28);
        coinEntry.add(dime);
        
        lblDime = new JLabel("Dime");
        lblDime.setBounds(143, 48, 33, 16);
        coinEntry.add(lblDime);
        
        quarter = new JTextField();
        quarter.setEditable(false);
        quarter.setColumns(10);
        quarter.setBounds(313, 40, 45, 28);
        coinEntry.add(quarter);
        
        lblQuarter = new JLabel("Quarter");
        lblQuarter.setBounds(251, 48, 47, 16);
        coinEntry.add(lblQuarter);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void quitAdminModeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    // Variables declaration - do not modify                     
    private javax.swing.JPanel adminModeSelection;
    private javax.swing.JPanel coinEntry;
    private javax.swing.JButton quitAdminModeButton;
    private javax.swing.JPanel Inventory;
    private javax.swing.JPanel cashBox;
    private javax.swing.JLabel title;
    private JLabel lblNickel;
    private JTextField nickle;
    private JTextField dime;
    private JLabel lblDime;
    private JTextField quarter;
    private JLabel lblQuarter;
    private JLabel lblNewLabel;
    private JTextField textField;
    private JTable table;
}
